config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :projects
  resources :contacts, only: [:new, :create]
  get 'welcome/index'
  root 'welcome#index'
  # get 'sign_in', to: 'devise/sessions#new'

  get '*path' => redirect('/')
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message,   :validate => true
  attribute :nickname,  :captcha => true

  def headers
    {
        :subject => 'Contact Form',
        :to => 'm.gogol.dev@gmail.com',
        :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "100%x700", thumb: "" },
                    convert_options: { thumb: "-gravity north -thumbnail 320x320^ -extent 320x320" }
                    # path: "/:class/:attachment/:id_partition/:style/:filename"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # :registerable,
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.all.order('created_at desc')
  end

  def new
    @contact = Contact.new
    @project = Project.new
  end

  def create
    @project = Project.new project_params
    if @project.save
      redirect_to @project, notice: 'Hey, Mykola! Your project is successfully saved.'
    else
      render 'new', notice: 'Oh, no! I was unable to save your project.'
    end
  end

  def show
    @contact = Contact.new
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project, notice: 'Your project successfully updated!'
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path
  end

  private
  def project_params
    params.require(:project).permit(:title, :description, :image, :slug)
  end

  def find_post
    @project = Project.friendly.find(params[:id])
    unless @project
      redirect_to root_path
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @projects = Project.all.limit(4).order('created_at desc')
    @contact = Contact.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(content)
    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
    options = {
        autolink: true,
        no_intra_emphasis: true,
        disable_indented_code_blocks: true,
        fenced_code_blocks: true,
        lax_spacing: true,
        strikethrough: true,
        superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_contact_form.html.erb
<div class="container">
  <div class="row contact_form_row">
    <%= simple_form_for @contact do |f| %>
        <div class="twelve columns">
          <%= f.input :name, required: true, placeholder: 'Your name', input_html: { id: 'name__Input', class: 'center_block contact_input' }, label: false %>
        </div>
        <div class="twelve columns">
          <%= f.input :email, required: true, placeholder: 'Email', input_html: { id: 'email__Input', class: 'center_block contact_input' }, label: false %>
        </div>
        <div class="twelve columns">
          <%= f.input :message, required: true, as: :text, input_html: { rows: '10', id: 'message__Input', class: 'center_block contact_input' }, placeholder: 'Hi Mykola ...', label: false %>
        </div>
        <div class="hidden">
          <%= f.input :nickname %>
        </div>
        <div class="three columns margin-none">
          <p></p>
        </div>
        <div class="four columns social_column">
          <a href="#" class="social_link_envelope"><i class="fa fa-envelope fa-2x" aria-hidden="true"></i></a>
          <a href="https://www.facebook.com/m.gogol.dev" class="social_link_facebook"><i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i></a>
        </div>
        <div class="three columns success_column">
          <%= f.submit 'Send', class: 'button-primary u-full-width', id: 'btn__sumbit' %>
        </div>
    <% end %>
  </div>
</div>

app/views/contacts/_form.html.erb
<div class="container">
  <div class="row contact_form_row">
    <%= simple_form_for @contact do |f| %>
        <div class="twelve columns">
          <%= f.input :name, required: true, placeholder: 'Your name', input_html: { id: 'name__Input', class: 'center_block contact_input' }, label: false %>
        </div>
        <div class="twelve columns">
          <%= f.input :email, required: true, placeholder: 'Email', input_html: { id: 'email__Input', class: 'center_block contact_input' }, label: false %>
        </div>
        <div class="twelve columns">
          <%= f.input :message, required: true, as: :text, input_html: { rows: '10', id: 'message__Input', class: 'center_block contact_input' }, placeholder: 'Hi Mykola ...', label: false %>
        </div>
        <div class="hidden">
          <%= f.input :nickname, hint: 'Leave this field blank!' %>
        </div>
        <div class="three columns margin-none">
          <p></p>
        </div>
        <div class="four columns social_column">
          <a href="#" class="social_link_envelope"><i class="fa fa-envelope fa-2x" aria-hidden="true"></i></a>
          <a href="https://www.facebook.com/m.gogol.dev" class="social_link_facebook"><i class="fa fa-facebook-official fa-2x" aria-hidden="true"></i></a>
        </div>
        <div class="three columns success_column">
          <%= f.submit 'Send', class: 'button-primary u-full-width', id: 'btn__sumbit' %>
        </div>
    <% end %>
  </div>
</div>

app/views/contacts/create.html.erb
<div class="container">
  <div class="row blank_wrapper">
    <div class="twelve columns vertical_align_center">
      <h1>Thanks for your message!</h1>
      <p class="text_center">I'll get back to you soon.</p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <%= favicon_link_tag 'tab_image.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Mykola Gogol | Personal Portfolio</title>
  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> -->
  <%= csrf_meta_tags %>
</head>
<body>
<noscript id="deferred-styles">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Raleway:200,300,400,600,700" rel="stylesheet">
  <!-- Skeleton CSS Framework CDN -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/skeleton/2.0.4/skeleton.min.css" integrity="sha256-2YQRJMXD7pIAPHiXr0s+vlRWA7GYJEK0ARns7k2sbHY=" crossorigin="anonymous" />
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
</noscript>
<script>
     var loadDeferredStyles = function() {
       var addStylesNode = document.getElementById("deferred-styles");
       var replacement = document.createElement("div");
       replacement.innerHTML = addStylesNode.textContent;
       document.body.appendChild(replacement)
       addStylesNode.parentElement.removeChild(addStylesNode);
     };
     var raf = requestAnimationFrame || mozRequestAnimationFrame ||
         webkitRequestAnimationFrame || msRequestAnimationFrame;
     if (raf) raf(function() { window.setTimeout(loadDeferredStyles, 0); });
     else window.addEventListener('load', loadDeferredStyles);
</script>
<!-- [HEADER] BEGIN -->
<div class="wrapper">
  <div class="header__container">
    <div class="row">
      <div class="button_container" id="toggle">
        <span class="top"></span>
        <span class="middle"></span>
        <span class="bottom"></span>
      </div>
      <div class="twelve columns header__navigation overlay" id="overlay">
        <div class="container navigation_container">
          <span class="nav_btn" onclick="menuBarToggle(this)">
            <div class="bar_1"></div>
            <div class="bar_2"></div>
            <div class="bar_3"></div>
          </span>
        </div>
        <nav class="overlay-menu">
          <%= link_to 'Mykola Gogol', root_path, class: 'logo__link' %>
          <%= link_to 'Home', root_path%>
          <!--<a href="#">About</a>-->
          <a href="#about_n_portfolio">About</a>
          <a href="#about_n_portfolio">Portfolio</a>
          <a href="#contact">Contact Me</a>
          <% if user_signed_in? %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'mobile_menu_element'%>
          <% end %>
        </nav>
      </div>
    </div>
  </div>
</div>
<hr>

<div class="container text_center flash_messages">
  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% elsif alert %>
    <p class="alert"><%= alert %></p>
  <% end %>
</div>
<!-- [HEADER] END -->
<%= yield %>

<!-- FOOTER -->
<footer>
  <div class="container">
    <div class="row">
      <div class="twelve columns">
        <a name="contact" href="#"></a>
        <p class="copyright_text">Copyright &copy; 2016 Mykola Gogol. All Rights Reserved.</p>
      </div>
    </div>
  </div>
</footer>
<script
src="https://code.jquery.com/jquery-3.1.1.min.js"
integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
crossorigin="anonymous"></script>

<script type="text/javascript" charset="utf-8">
  $('span.nav_btn').click(function () {
    $('nav.overlay-menu').slideToggle();
  });

  function menuBarToggle(x) {
    x.classList.toggle('change');
  }

  // Scroll to a certain element
  $(function() {
    $('a[href*="#"]:not([href="#"])').click(function() {
      if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
        var target = $(this.hash);
        target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
        if (target.length) {
          $('html, body').animate({
            scrollTop: target.offset().top
          }, 1000);
          return false;
        }
      }
    });
  });

</script>

<!-- Yandex.Metrika counter -->
<!-- <script type="text/javascript">
  (function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
      try {
        w.yaCounter41266794 = new Ya.Metrika({
          id:41266794,
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true
        });
      } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = "https://mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
      d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/41266794" style="position:absolute; left:-9999px;" alt="" /></div></noscript> -->
<!-- /Yandex.Metrika counter -->

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-88274236-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/projects/_form.html.erb
<div class="container">
  <div class="row input__row">
    <%= simple_form_for @project do |f| %>
        <% if @project.errors.any? %>
            <!-- true -->
            <h2><%= pluralize(@project.errors.count, "error") %> prevented this post from saving!</h2>
            <ul>
              <% @project.errors.full_messages.each do |msg| %>
                  <li><% msg %></li>
              <% end %>
            </ul>
        <% end %>

        <%= f.input :title, label: 'Title'%>
        <%= f.input :image %>
        <%= f.input :description, label: 'Your description here...' %> <br>
        <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Edit post</h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="container">
  <h1 class="main_title">All Projects</h1>
  <div class="row">
    <% @projects.each do |project| %>
        <div class="four columns portfolio_item_show_column">
          <div>
            <%= link_to image_tag(project.image.url(:thumb)), project, class: 'portfolio_item_show' %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<h1>New post</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<div class="container">
  <div class="row">
    <div class="twelve columns">
      <h2 class="text_center project__title"><%= @project.title %></h2>
    </div>
  </div>
  <div class="row">
    <div class="twelve columns">
      <%= image_tag @project.image.url(:medium), class: 'u-max-full-width center_block' %>
    </div>
  </div>
  <div class="row">
    <div class="ten columns u-cf center_block description__block">
      <p class="project__description"><%= markdown @project.description %></p>
    </div>
  </div>
  <% if user_signed_in? %>
    <div class="row">
      <div class="two columns edit__buttons_column u-cf center_block">
        <%= link_to 'Edit', edit_project_path(@project) %>
        <%= link_to 'Delete', project_path(@project), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
  <% end %>
</div>
<!-- Contact Form Rendering -->
<div class="row">
  <div class="twelve columns contact_me">
    <p class="main_title">Let's Work Together</p>
    <p class="contact_me__description">I’m always available for awesome projects, get in touch!</p>
    <hr>
  </div>
</div>
<%= render 'contacts/form' %>

app/views/welcome/index.html.erb
<!-- [SECOND BLOCK] BEGIN -->
<div class="container">
  <div class="row">
    <div class="twelwe columns title__column">
      <h3>Hey, I'm Mykola Gogol</h3>
      <p>Web Developer</p>
      <hr>
    </div>
  </div>
  <div class="row">
    <div class="twelwe columns title__column">
      <h1>I DESIGN <span id="span__ampersant">&amp;</span> DEVELOP <span id="span__website">WEBSITES</span></h1>
    </div>
  </div>
</div>
<!-- Computer Image -->
<div class="container">
  <div class="row">
    <div class="twelwe columns image__column">
      <%= image_tag 'computer_min.png', alt: 'Computer Image', class: 'u-max-full-width' %>
    </div>
  </div>
</div>
<!-- [SECOND BLOCK] END -->

<!-- [THIRD] BLOCK BEGIN -->
<div class="wrapper">
  <div class="container">
    <div class="row third__block">
      <div class="twelwe columns quote__column">
        <blockquote>Websites promote you 24/7: No employee will do that.</blockquote>
        <hr>
      </div>
    </div>
    <!-- [THIRD] BLOCK END -->
    <!-- [FOUR BLOCK] BEGIN -->
    <a id="about_n_portfolio"></a>
    <div class="row">
      <div class="six columns about-me__column">
        <p class="main_title">About Me</p>
        <hr>
        <div class="row">
          <div class="three columns">
            <%= image_tag 'photo.jpg', alt: 'Mykola Gogol Photo', class: 'profile_image' %>
          </div>
          <div class="eight columns">
            <p class="name_title"><b>Mykola Gogol</b></p>
            <p>
              <span class="skill_text ruby_text">Ruby on Rails</span>
              <span class="skill_text js_text">JS</span>
              <span class="skill_text html_text">HTML&CSS</span>
              <span class="skill_text wordpress_text">Wordpress</span>
              <span class="skill_text bootstrap_text">Bootstrap</span>
              <span class="skill_text jquery_text">jQuery</span>
              <span class="skill_text angular_text">AngularJS</span>
            </p>
            <!--<p><b>3 years</b> of work experience</p>-->
            <p class="inspiring_text">3 years of work experience.</p>
          </div>
        </div>
        <p>
          <b>Hello there, My Friend</b><br>
          I'm a programmer & designer with warm feelings to Web Development, from Ukraine, Ivano-Frankivsk.
          <br><br>
          Starting with basic websites several years ago I found for myself that is my passion.
          And now I'm looking for challenging projects and opportunities to help people achieve their goals.

          <br><br><b>I Can Help.</b><br>
          I love meeting new people and learning about their businesses, so if you feel that I can help you,
          I look forward to working with you soon. Communication is present during the whole working process. Message me and let's start!
      </div>
      <div class="six columns portfolio__column">
        <p class="main_title">Check My Portfolio</p>
        <hr>
        <div class="row">
          <% @projects.each do |project| %>
              <div class="portfolio__item"><%= link_to image_tag(project.image.url(:thumb)), project %></div>
          <% end  %>
        </div>
        <!--<div class="row">-->
          <!--<div class="twelve columns">-->
            <!--<%= link_to 'View All', projects_path, class: 'view_all_button u-pull-right' %>-->
          <!--</div>-->
        <!--</div>-->
      </div>
    </div>
    <!-- [FOUR BLOCK] END -->
  </div>
</div>
<!-- [CONTACT ME] BEGIN -->
<a id="contact"></a>
  <div class="row">
    <div class="twelve columns contact_me">
      <p class="main_title">Say Hello!</p>
      <p class="contact_me__description">I’m always available for awesome projects, get in touch!</p>
      <hr>
    </div>
  </div>

  <!-- Contact Form Rendering -->
  <%= render 'contacts/form' %>

  </form>
</div>
<!-- [CONTACT ME] END -->